FEDERATION_SERVER="https://api.stellar.org/federation"
TRANSFER_SERVER="https://api.stellar.org/auth"
HORIZON_URL="https://horizon.stellar.org"

ACCOUNTS=["GDVWPEOTJOPRT433PX6LULEPML5AN6QJO4GCFVFK43IPRQ23NPQAUSDF",
"GDO6ZJO6TRDGW5BP3H3MNICDTWL4WS45Y3BZCN4D42VM5RC6NIXLYWLX"]

[DOCUMENTATION]

ORG_NAME="Aquapod Association"
ORG_URL="https://aquapodassociation.pages.dev/"
ORG_LOGO="aquapodassociation.pages.dev/images/Aquapod.png"
ORG_DESCRIPTION="Aquapod owners association"
ORG_PHYSICAL_ADDRESS="Los Angeles, CA 90067, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION="https://aquapodassociation.pages.dev/docblprivate.pdf"
ORG_PHONE_NUMBER="+18446612487"
ORG_PHONE_NUMBER_ATTESTATION="phn.pdf"
ORG_KEYBASE="aquapod*keybase.io"

ORG_TWITTER=""
ORG_GITHUB=""
ORG_OFFICIAL_EMAIL=""

[[PRINCIPALS]]
name="sass"
email=""
keybase=""
twitter=""
github=""
id_photo_hash=""
verification_photo_hash=""

[[CURRENCIES]]
code="AQUAPODASSOC"
issuer="GBBT7SR6TODAKWJDG3NJEARPRQEDKO6AAR35Q36YQZP6367FQASLLW3F"
display_decimals=4
name="Aquapod Association"
desc="Fungible base/counter cryptocurrency. t.me/aquapod_bot / @aquapod_bot"
conditions="Verified mint. Active burn policy. Issuer may mint additional tokens."
image="https://aquapodassociation.pages.dev/images/Aquapod.png"
fixed_number=1000000000
